arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_pitch_joint
    - elbow_roll_joint
    - elbow_pitch_joint
    - wrist_roll_joint
    - wrist_pitch_joint
    - gripper_roll_joint
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pitch_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_roll_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_joint1
    - finger_joint2
  gains:
    finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    finger_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1